#
# Copyright 2024 the Operaton contributors.
# <p>
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# <p>
# https://www.apache.org/licenses/LICENSE-2.0
# <p>
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
type: specs.openrewrite.org/v1beta/recipe
name: org.operaton.rewrite.quarkus.MigrateQuarkusApplication
description: Migrate a Quarkus application from Camunda to Operaton.
displayName: Migrate a Quarkus application from Camunda to Operaton
recipeList:
  - org.operaton.rewrite.ReplaceCamundaDependencies
  - org.operaton.rewrite.ChangeMethod
  - org.operaton.rewrite.ChangeConstant
  - org.operaton.rewrite.ChangeType
  - org.operaton.rewrite.ChangePackage
  - org.operaton.rewrite.MigrateDeploymentDescriptors
  - org.openrewrite.quarkus.DeleteQuarkusProperty:
      propertyKey: camunda.bpm.license-file
  - org.openrewrite.quarkus.ChangeQuarkusPropertyKey:
      oldPropertyKey: quarkus\.camunda(.*)
      newPropertyKey: quarkus\.operaton$1
